'use strict';
const data=JSON.parse(document.getElementById('research-data').textContent),$=id=>document.getElementById(id);
const ns='http://www.w3.org/2000/svg',stateNames={constraint:'제약 확인',watch:'주의 관찰',easing:'완화 근거',adequate:'충족 근거',unknown:'판단 보류'};
const typeNames={reference:'확인 전 참고 연결',technical:'검토한 기술 의존',observed:'관측된 지연 전파',conditional:'조건부 전파'};
const statusNames={uninvestigated:'미조사',in_progress:'조사 중',review_recorded:'검토 기록 있음'};
const natureNames={observation:'실제 관측',external_plan:'외부 계획',external_forecast:'외부 전망',inference:'해석',scenario:'조건부 시나리오'};
function el(tag,text,parent,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;parent?.append(e);return e}
function svg(tag,attrs,parent){const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));parent.append(e);return e}
function str(v){return Array.isArray(v)?v.join(' / '):v??'미확인'}
function link(parent,url,label){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw Error();const a=el('a',label,parent);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer'}catch{el('span',label+' · 원문 주소 미확인',parent,'muted')}}
const nodes=data.nodes?.length?data.nodes:data.rows.map(r=>({node_id:r.judgment_id,name:r.segment,module:'Other',judgments:[r],sources:r.sources,events:[],questions:[],summary:r.conclusion,research_status:'review_recorded'}));
const byId=new Map(nodes.map(n=>[n.node_id,n]));
const edges=(data.nodes?.length?data.node_relations:data.relations.map(e=>({...e,from_node_id:e.from_judgment_id,to_node_id:e.to_judgment_id}))).filter(e=>byId.has(e.from_node_id)&&byId.has(e.to_node_id));
let selected=null,selectedRow=null,detail='trend',mapMode=false,expanded=false,scale=1,pan={x:0,y:0};
function sole(n){return n.judgments.length===1?n.judgments[0]:null}
function score(r){if(!r?.score)return null;return (r.score.low===r.score.high?String(r.score.low):r.score.low+'–'+r.score.high)+(r.score.provisional?'*':'')}
function state(n){return sole(n)?.qualitative_state||'unknown'}
function label(n){const r=sole(n);return score(r)||(n.judgments.length>1?'범위별 상이':r?(stateNames[state(n)]||'정성 판단'):n.research_status==='uninvestigated'?'미조사':'판단 보류')}
function arrow(r){return {strengthening:'↑',easing:'↓',unchanged:'→',unknown:'·'}[r?.trend?.direction]||'·'}
function scopeText(r){return [r.scope.geography,r.scope.product_spec,r.scope.horizon,r.scope.scenario].join(' · ')}
function important(n){return n.judgments.some(r=>data.highlight_ids?.includes(r.judgment_id))}
$('date').textContent=data.as_of_date+' 기준';
$('coverage-note').textContent=`${nodes.length}개 구간 · ${data.rows.length}개 판단 범위 · ${data.research_stage==='baseline_review'?'검토용 결과':'조사 중간 결과'}`;
$('data-note').textContent='목록은 공급망 순서이며 전체 순위가 아닙니다. 숫자가 없으면 정성 판단을 표시합니다. * 잠정 점수 · 추세 미확인';
function monitor(){const box=$('monitor');box.replaceChildren();const query=$('monitor-search').value.trim().toLowerCase();const all=nodes.filter(n=>(n.name+' '+n.node_id).toLowerCase().includes(query));let shown=all;
 if(!expanded&&!query){const highlight=all.filter(important);shown=(highlight.length?highlight:all.filter(n=>n.judgments.length)).slice(0,8);if(!shown.length)shown=all.slice(0,8)}
 for(const n of shown){const b=el('button',undefined,box,'monitor-row');b.dataset.id=n.node_id;b.setAttribute('aria-pressed',String(selected?.node_id===n.node_id));el('span',n.name,b,'name');el('span',label(n),b,'score '+(score(sole(n))?'numeric':'qualitative tone-'+state(n)));const a=el('span',arrow(sole(n)),b,'direction');a.title=sole(n)?.trend?.label||'추세 미확인';b.onclick=()=>choose(n)}
 if(!shown.length)el('p','검색어에 맞는 구간이 없습니다.',box,'empty');$('list-count').textContent=`${shown.length} / ${nodes.length}개 구간 표시`;$('show-all').textContent=expanded?'핵심 목록':'전체 목록';
}
function sourceList(parent,sources){if(!sources.length)el('p','아직 연결된 원문이 없습니다.',parent,'muted');for(const s of sources){const p=el('div',undefined,parent,'source');el('p',s.claim||'자료 검토 기록',p);link(p,s.url,s.producer+' · '+(s.published_at||'발표일 미확인'));el('p',[s.role,natureNames[s.nature],s.location].filter(Boolean).join(' · '),p,'micro');if(s.capture_kind==='search_trace')el('p','검색 기록입니다. 확인한 원문으로 간주하지 않습니다.',p,'muted');if(s.capture_kind==='extracted_text')el('p','호스트가 가져온 원문 발췌입니다.',p,'muted')}}
function inspector(){const brief=$('brief');brief.replaceChildren();if(!selected){el('p','구간을 선택하면 설명과 근거를 볼 수 있습니다.',brief,'muted');$('detail-content').replaceChildren();return}
 el('h2',selected.name,brief);if(selected.judgments.length>1){const select=el('select',undefined,brief);select.id='scope-select';select.setAttribute('aria-label','판단 범위 선택');el('option','판단 범위를 선택하세요',select).value='';for(const r of selected.judgments)el('option',scopeText(r),select).value=r.judgment_id;select.value=selectedRow?.judgment_id||'';select.onchange=()=>{selectedRow=selected.judgments.find(r=>r.judgment_id===select.value)||null;inspector()}}
 const r=selectedRow;el('p',r?.conclusion||selected.summary,brief);el('div',r?scopeText(r):statusNames[selected.research_status]||'검토 기록',brief,'scope');
 if(r){el('div','최근 근거 공개: '+(r.publication_dates?.at(-1)||'미확인')+' · 관측 시점: '+(r.observation_dates?.at(-1)||'미확인'),brief,'scope');const more=el('details',undefined,brief,'explanation');el('summary','판단 이유와 남은 질문',more);el('p',r.reasoning,more);el('p','다른 설명: '+str(r.alternatives),more);el('p','아직 모르는 점: '+str(r.unknowns),more);el('p','다음에 확인할 것: '+str(r.next_actions),more);el('p','판단 확실성: '+({Low:'낮음',Medium:'중간',High:'높음'}[r.confidence]||'미확인'),more);el('p','실제 가동 제약: '+({ObservedBinding:'관측 근거 있음',ConditionalBinding:'조건부',DemonstratedNonBinding:'해당 범위에서 비구속 확인',NotDemonstrated:'입증되지 않음'}[r.binding_status]||'입증되지 않음'),more)}
 else if(selected.questions.length){const more=el('details',undefined,brief,'explanation');el('summary','노드별 조사 내용',more);for(const q of selected.questions){el('strong',q.question,more);el('p',q.answer||q.next_action||'조사 중',more);if(q.remaining_uncertainty)el('p','남은 공백: '+q.remaining_uncertainty,more)}}
 showDetail(detail);
}
function choose(n){selected=n;selectedRow=sole(n);$('map-select').value=n.node_id;monitor();inspector();if(mapMode)draw()}
function showDetail(which){detail=which;document.querySelectorAll('[data-detail]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.detail===which)));const d=$('detail-content');d.replaceChildren();if(!selected){el('p','먼저 구간을 선택해 주세요.',d,'muted');return}const r=selectedRow;
 if(which==='evidence'){sourceList(d,r?.sources||selected.sources);return}
 if(which==='companies'){const companies=r?.companies||[];for(const c of companies){el('strong',c.name,d);el('p',c.role,d)}if(!companies.length)el('p',selected.judgments.length>1&&!r?'판단 범위를 먼저 선택해 주세요.':'근거로 연결한 기업이 아직 없습니다.',d,'muted');return}
 if(r)el('p',r.trend.label+' · '+r.trend.reason,d);
 const points=r?.history||[];
 if(points.length>=2){const g=svg('svg',{viewBox:'0 0 640 160',class:'chart',role:'img','aria-label':'비교 가능한 최근 6개월 점수 이력'},d),lo=Date.parse(points[0].date),hi=Date.parse(points.at(-1).date),x=p=>40+560*(Date.parse(p.date)-lo)/(hi-lo||1),y=n=>125-n;
 for(const n of [0,50,100]){svg('line',{x1:35,x2:610,y1:y(n),y2:y(n),stroke:'var(--line)'},g);svg('text',{x:0,y:y(n)+4},g).textContent=n}svg('path',{d:points.map((p,i)=>(i?'L':'M')+x(p)+','+y(p.low)).join(' '),fill:'none',stroke:'var(--blue)','stroke-width':2},g);for(const p of points){svg('line',{x1:x(p),x2:x(p),y1:y(p.low),y2:y(p.high),stroke:'var(--blue)','stroke-width':6,opacity:.3},g);svg('circle',{cx:x(p),cy:y(p.low),r:3,fill:'var(--blue)'},g);svg('text',{x:x(p),y:150,'text-anchor':'middle'},g).textContent=p.date.slice(5)}
 }else el('p','최근 6개월의 비교 가능한 점수가 충분하지 않습니다. 추세선은 만들지 않았습니다.',d,'muted');
 const scopeKey=s=>JSON.stringify(Object.entries(s).filter(([k])=>k!=='as_of_date').sort());const events=selected.events.filter(e=>!r||scopeKey(e.scope)===scopeKey(r.scope)).sort((a,b)=>a.event_date.localeCompare(b.event_date));
 if(events.length){el('h3','관측·계획 이력',d);el('p','사건 기록이며 점수 추세와는 다릅니다. 과거 계획과 실현을 구분해 읽어 주세요.',d,'micro');for(const e of events){const p=el('div',undefined,d,'timeline-item');const nature=[...new Set(e.sources.map(s=>natureNames[s.nature]||'미분류'))].join(' / ');el('span',e.event_date+' · '+nature,p,'micro');el('p',e.description,p);for(const s of e.sources)link(p,s.url,s.producer+' · '+(s.published_at||'발표일 미확인'))}}
 else el('p','이 범위에 연결된 과거 관측·계획 이력은 아직 없습니다.',d,'muted');
}
document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));$('show-all').onclick=()=>{expanded=!expanded;monitor()};$('monitor-search').oninput=monitor;
for(const n of nodes)el('option',n.name,$('map-select')).value=n.node_id;
// Collapse strongly connected components, then place acyclic dependencies left to right.
const ids=nodes.map(n=>n.node_id),adj=new Map(ids.map(id=>[id,[]]));for(const e of edges)adj.get(e.from_node_id).push(e.to_node_id);
let seq=0,stack=[],index=new Map(),low=new Map(),active=new Set(),groups=[];
function visit(v){index.set(v,seq);low.set(v,seq++);stack.push(v);active.add(v);for(const w of adj.get(v)){if(!index.has(w)){visit(w);low.set(v,Math.min(low.get(v),low.get(w)))}else if(active.has(w))low.set(v,Math.min(low.get(v),index.get(w)))}if(low.get(v)===index.get(v)){const group=[];let w;do{w=stack.pop();active.delete(w);group.push(w)}while(w!==v);groups.push(group)}}ids.forEach(v=>{if(!index.has(v))visit(v)});
const groupOf=new Map();groups.forEach((g,i)=>g.forEach(v=>groupOf.set(v,i)));const level=groups.map(()=>0),degree=groups.map(()=>0),outs=groups.map(()=>new Set());for(const e of edges){const a=groupOf.get(e.from_node_id),b=groupOf.get(e.to_node_id);if(a!==b&&!outs[a].has(b)){outs[a].add(b);degree[b]++}}const queue=degree.map((n,i)=>n===0?i:-1).filter(i=>i>=0);while(queue.length){const a=queue.shift();for(const b of outs[a]){level[b]=Math.max(level[b],level[a]+1);if(--degree[b]===0)queue.push(b)}}
const columns=new Map();for(const n of nodes){const l=level[groupOf.get(n.node_id)];if(!columns.has(l))columns.set(l,[]);columns.get(l).push(n)}
const W=Math.max(1000,(Math.max(0,...level)+1)*220+100),H=Math.max(650,...[...columns.values()].map(a=>a.length*74+100)),positions=new Map();
for(const[l,items]of columns)items.forEach((n,i)=>positions.set(n.node_id,{x:80+l*220+(i%2)*30,y:60+(i+.5)*(H-120)/items.length}));
// Barycenter ordering reduces crossings without moving a node to a different supply stage.
for(let iteration=0;iteration<8;iteration++)for(const[l,items]of columns){const mid=n=>{const related=edges.filter(e=>e.to_node_id===n.node_id||e.from_node_id===n.node_id).map(e=>positions.get(e.to_node_id===n.node_id?e.from_node_id:e.to_node_id).y);return related.length?related.reduce((a,b)=>a+b)/related.length:positions.get(n.node_id).y};items.sort((a,b)=>mid(a)-mid(b));items.forEach((n,i)=>positions.get(n.node_id).y=60+(i+.5)*(H-120)/items.length)}
function unit(){const box=$('graph').getBoundingClientRect();return 1/Math.max(.05,Math.min(box.width/W,box.height/H))}
function radius(n,upper=false){const r=sole(n);return (r?.score?6+Math.sqrt((upper?r.score.high:r.score.low)/100)*15:state(n)==='unknown'?3.5:7)*unit()}
function tone(n){const r=sole(n);if(r?.score)return `color-mix(in srgb,var(--red) ${r.score.low}%,var(--subtle))`;return {constraint:'var(--red)',watch:'var(--gold)',easing:'var(--blue)',adequate:'var(--blue)',unknown:'var(--subtle)'}[state(n)]}
function transform(){const scene=$('scene');if(scene)scene.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${scale})`);$('graph').classList.toggle('zoomed',scale>=1.7)}
function filteredEdges(){return edges.filter(e=>$('edge-filter').value==='all'||e.kind===$('edge-filter').value)}
function draw(){const g=$('graph');g.replaceChildren();g.setAttribute('viewBox',`0 0 ${W} ${H}`);const defs=svg('defs',{},g),marker=svg('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto'},defs);svg('path',{d:'M0 0L10 5L0 10Z',fill:'var(--subtle)'},marker);const scene=svg('g',{id:'scene'},g);transform();const query=$('search').value.trim().toLowerCase(),filtered=filteredEdges(),neighbors=new Set(selected?[selected.node_id]:[]);if(selected)for(const e of filtered){if(e.from_node_id===selected.node_id)neighbors.add(e.to_node_id);if(e.to_node_id===selected.node_id)neighbors.add(e.from_node_id)}
 for(const e of filtered){const a=positions.get(e.from_node_id),b=positions.get(e.to_node_id),dx=b.x-a.x,dy=b.y-a.y,angle=Math.atan2(dy,dx),r1=radius(byId.get(e.from_node_id),true)+4,r2=radius(byId.get(e.to_node_id),true)+7,x1=a.x+Math.cos(angle)*r1,y1=a.y+Math.sin(angle)*r1,x2=b.x-Math.cos(angle)*r2,y2=b.y-Math.sin(angle)*r2;const path=svg('path',{class:'edge '+e.kind+(selected&&![e.from_node_id,e.to_node_id].includes(selected.node_id)?' dim':''),d:`M${x1} ${y1} Q${(x1+x2)/2+((Math.abs(dx)<80)?35:0)} ${(y1+y2)/2} ${x2} ${y2}`,'marker-end':'url(#arrow)','vector-effect':'non-scaling-stroke'},scene);svg('title',{},path).textContent=(typeNames[e.kind]||e.kind)+': '+e.reason}
 let matches=0;for(const n of nodes){const match=(!query||(n.name+' '+n.node_id).toLowerCase().includes(query))&&($('state-filter').value==='all'||($('state-filter').value==='uninvestigated'?n.research_status==='uninvestigated':state(n)===$('state-filter').value));if(match)matches++;const p=positions.get(n.node_id),dim=!match||(selected&&!neighbors.has(n.node_id));const group=svg('g',{class:'node'+(dim?' dim':'')+(important(n)||selected?.node_id===n.node_id||query&&match?' labeled':''),transform:`translate(${p.x} ${p.y})`,tabindex:0,role:'button','aria-label':n.name+' · '+label(n),'aria-pressed':String(selected?.node_id===n.node_id),'data-id':n.node_id},scene);svg('title',{},group).textContent=n.name+' · '+label(n);const r=sole(n);if(r?.score&&r.score.high>r.score.low)svg('circle',{r:radius(n,true),fill:'none',stroke:tone(n),opacity:.45,'vector-effect':'non-scaling-stroke'},group);svg('circle',{class:'core',r:radius(n),fill:r?.score?tone(n):'var(--panel)',stroke:tone(n),'stroke-width':r?.score?1:state(n)==='unknown'?1:2,'stroke-dasharray':state(n)==='unknown'&&!r?.score?'3 3':'none','vector-effect':'non-scaling-stroke'},group);const text=svg('text',{'text-anchor':p.x<200?'start':p.x>W-200?'end':'middle',y:radius(n,true)+17*unit(),class:'node-label',style:`font-size:${12*unit()}px;stroke-width:${4*unit()}px`},group);text.textContent=n.name.length>27?n.name.slice(0,26)+'…':n.name;group.onclick=()=>{if(!moved)choose(n)};group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(n)}}}
 $('graph-note').textContent=`${nodes.length}개 전체 구간 · 조건 일치 ${matches}개 · 연결 ${filtered.length}개${selected?' · 선택 구간의 연결 강조':''}`;
 $('cycle-note').textContent=groups.some(g=>g.length>1)?'공급 흐름은 왼쪽→오른쪽입니다. 서로 의존하는 구간은 같은 단계에 놓습니다.':'공급 흐름은 왼쪽→오른쪽입니다.';
 const rel=$('relation-detail');rel.replaceChildren();if(selected){const connected=filtered.filter(e=>e.from_node_id===selected.node_id||e.to_node_id===selected.node_id);el('summary',`연결 설명 (${connected.length})`,rel);for(const e of connected){const p=el('div',undefined,rel,'source');el('strong',byId.get(e.from_node_id).name+' → '+byId.get(e.to_node_id).name,p);el('p',(typeNames[e.kind]||e.kind)+' · '+e.reason,p);for(const s of e.sources||[])link(p,s.url,s.producer)}}rel.classList.toggle('hidden',!selected);
}
function mode(map){mapMode=map;$('dashboard').classList.toggle('hidden',map);$('map').classList.toggle('hidden',!map);$('dashboard-tab').setAttribute('aria-pressed',String(!map));$('map-tab').setAttribute('aria-pressed',String(map));(map?$('map-inspector'):$('dashboard-inspector')).append($('inspector'));if(map)draw()}
$('dashboard-tab').onclick=()=>mode(false);$('map-tab').onclick=()=>mode(true);$('search').oninput=draw;$('edge-filter').onchange=draw;$('state-filter').onchange=draw;$('map-select').onchange=()=>{if(byId.has($('map-select').value))choose(byId.get($('map-select').value))};
function zoom(factor,x=W/2,y=H/2){const next=Math.max(.4,Math.min(7,scale*factor)),ratio=next/scale;pan={x:x-(x-pan.x)*ratio,y:y-(y-pan.y)*ratio};scale=next;transform()}
$('zoom-in').onclick=()=>zoom(1.3);$('zoom-out').onclick=()=>zoom(1/1.3);$('reset').onclick=()=>{scale=1;pan={x:0,y:0};selected=null;selectedRow=null;$('map-select').value='';$('search').value='';$('state-filter').value='all';$('edge-filter').value='all';monitor();inspector();draw()};
let drag=null,moved=false;function point(e){const p=$('graph').createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform($('graph').getScreenCTM().inverse())}
$('graph').onpointerdown=e=>{if(e.button!==0)return;const p=point(e);drag={x:p.x,y:p.y,pan:{...pan}};moved=false;$('graph').setPointerCapture(e.pointerId)};
$('graph').onpointermove=e=>{if(!drag)return;const p=point(e),dx=p.x-drag.x,dy=p.y-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved){pan={x:drag.pan.x+dx,y:drag.pan.y+dy};transform()}};
$('graph').onpointerup=()=>{drag=null};$('graph').onpointercancel=()=>{drag=null};$('graph').addEventListener('wheel',e=>{e.preventDefault();const p=point(e);zoom(e.deltaY<0?1.12:1/1.12,p.x,p.y)},{passive:false});
monitor();inspector();
window.addEventListener('resize',()=>{if(mapMode)draw()});
